language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
install:
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
  - chmod a+x ./publish/entrypoint.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      all_branches: true